### ISSUE TITLE
two types of endorsements

### ISSUE THREAD

**Issue by thomas-fossati** [dthaler/rats-endorsements-old#2]
There are (at least) two types of objects that are currently wrapped under the "endorsement" term:

* _identity_ endorsement (e.g., verification keys)
* endorsed _values_ (e.g., certification status, colour, etc.)

It is important to make that distinction because of the pretty different role they play in evidence verification.

See also https://github.com/ietf-rats-wg/draft-ietf-rats-corim/wiki/verification-schematic

**Comment by dthaler** [comment]
@thomas-fossati how is an "identity endorsement" different from an "endorsed values" endorsement, where the value is the identity?   (or suggest text if you prefer)

**Comment by dthaler** [comment]
Added text in draft-01.
If it is not sufficient, please open an issue in the newer repo.
