### ISSUE TITLE
conditional endorsements

### ISSUE THREAD

**Issue by thomas-fossati** [dthaler/rats-endorsements-old#3]
It may be worth in this document articulating the concept of _conditional_ endorsements, i.e., _endorsed values_ (see #2) that apply only if evidence matches certain measurements.  A typical example being the certification status assigned to a specific snapshot of the device TCB, which is conditional on evidence matching the measurements of said TCB.

**EDITED(tho) (Tue 11 Jul 2023 14:58:15 BST):** s/ref-values/measurements/

**Comment by dthaler** [comment]
Added text in draft-01.
If it is not sufficient, please open an issue in the newer repo.
